import os


HEIGHT = 8
WIDTH = 8
FRAME_RATE = 15

GENERATION_SIZE = 60
MUTATION_CHANCE = 0.10
TRAINING_TIME_LIMIT = 1000
GENERATIONS = 1000
EVALUATIONS = 5

MODEL_PATH = os.path.join(os.getcwd(), "bin", "model.pth")
